(cl:defpackage create_node-msg
  (:use )
  (:export
   "<BATTERYSTATE>"
   "BATTERYSTATE"
   "<CREATE2SENSORSTATE>"
   "CREATE2SENSORSTATE"
   "<DRIVE>"
   "DRIVE"
   "<RAWTURTLEBOTSENSORSTATE>"
   "RAWTURTLEBOTSENSORSTATE"
   "<ROOMBASENSORSTATE>"
   "ROOMBASENSORSTATE"
   "<TURTLE>"
   "TURTLE"
   "<TURTLEBOTSENSORSTATE>"
   "TURTLEBOTSENSORSTATE"
  ))

